#! /bin/sh

source $HOME/.config/scripts/use_default_screen.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-2 -d 1 2 3 4 5 6 7 8

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#313244"
bspc config focused_border_color "#7f849c"

$HOME/.fehbg
$HOME/.config/polybar/launch.sh
# picom -fb &
