#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap -layout us &

$HOME/.config/scripts/home.sh &
# source $HOME/.config/scripts/use_default_screen.sh &

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

if (xrandr --query | grep 'HDMI.* connected' | cut -d ' ' -f1); then
    bspc monitor HDMI-2 -d 1 2 3 4 5
    bspc monitor eDP-1 -d 6 7 8 9 10
    bspc wm --reorder-monitors HDMI-2 eDP-1
else
    bspc monitor -d 1 2 3 4 5 6
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#313244"
bspc config focused_border_color "#7f849c"

$HOME/.fehbg &
$HOME/.config/polybar/launch.sh &
# picom -fb &
