-- Vanilla Config
require('configs.settings')
require('configs.plugins')
require('configs.keybinds')
require('configs.telescope')
require('configs.treesitter')
require('configs.colors')
require('configs.lsp')
require('configs.toggleterm')
require('configs.nvim-tree')
-- require('configs.autocmd')
